export const serviceFailureScenarios = {
  uploadFailed: {
    label: "上传失败",
    identity_context: {
      user_id: "user_001",
      display_name: "Student A",
      organization_id: "course_001",
      role: "student",
    },
    upload_record: {
      upload_id: "upl_006",
      storage_ref: "unavailable",
      filename: "large-report.pdf",
      sha256: "未生成",
      status: "failed",
    },
    asset_version: {
      asset_id: "未创建",
      asset_type: "lab_report",
      version_no: 0,
      previous_version_id: null,
      sha256: "未生成",
      submitter_id: "user_001",
      timestamp: "未创建",
    },
    verification_result: {
      status: "failed",
      receipt_status: "missing",
      trace_status: "missing",
      digest_match: null,
      failure_reason: "upload_failed",
    },
    proof: {
      receipt_id: "未创建",
      trace_id: "未创建",
      transaction_hash: "未创建",
      timestamp: "未创建",
    },
    ai_explanation: {
      summary: "文件上传未完成，系统没有生成可用于证明的资产版本或回执。",
      risks: ["当前没有可核验的 digest、receipt 或 trace。"],
      next_checks: ["重新上传文件。", "检查文件大小、网络状态和本地存储服务。"],
      confidence_note: "AI 解释不构成真实性证明，证明来源为结构化回执与验证结果。",
    },
    timeline: [],
  },
  aiExplanationUnavailable: {
    label: "AI 解释不可用",
    identity_context: {
      user_id: "user_001",
      display_name: "Student A",
      organization_id: "course_001",
      role: "student",
    },
    upload_record: {
      upload_id: "upl_007",
      storage_ref: "dualweave://upl_007",
      filename: "experiment8-report-ai-timeout.pdf",
      sha256: "a98f76543210fedcba00112233445566778899aabbccddeeff00112233445566",
      status: "stored",
    },
    asset_version: {
      asset_id: "asset_007",
      asset_type: "lab_report",
      version_no: 1,
      previous_version_id: null,
      sha256: "a98f76543210fedcba00112233445566778899aabbccddeeff00112233445566",
      submitter_id: "user_001",
      timestamp: "2026-05-08 15:05",
    },
    verification_result: {
      status: "verified",
      receipt_status: "available",
      trace_status: "available",
      digest_match: true,
      failure_reason: "ai_explanation_unavailable",
    },
    proof: {
      receipt_id: "rcpt_007",
      trace_id: "trace_007",
      transaction_hash: "0x91bc274eb33fa48e92a5d3310cdd5a08",
      timestamp: "2026-05-08 15:05:00",
    },
    ai_explanation: {
      summary: "结构化回执与核验结果可用，但 AI 解释服务暂时不可用。",
      risks: ["AI 文案缺失不影响 digest、receipt、trace 和 verification result 的证明地位。"],
      next_checks: ["人工查看回执字段。", "稍后重试 AI explanation 服务。"],
      confidence_note: "AI 解释不可用时，证明来源仍然是结构化回执与验证结果。",
    },
    timeline: [
      {
        version: "v1",
        digest: "a98f...5566",
        status: "verified",
        time: "2026-05-08 15:05",
        previous_version_id: "无",
      },
    ],
  },
};
